apiVersion: apps/v1
kind: Deployment
metadata:
  name: pro1
  labels:
    app: pro1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pro1
  template:
    metadata:
      labels:
        app: pro1
    spec:
      containers:
        - image: kingzim/pro1:45
          name: pro1-container
          ports:
            - containerPort: 9999
