apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pro1
    app.kubernetes.io/instance: dev
  name: pro1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pro1
  template:
    metadata:
      labels:
        app: pro1
    spec:
      containers:
        - image: 'kingzim/pro1:41'
          name: pro1-container
          ports:
            - containerPort: 9999
