apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dev
  name: pro1-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9999
  selector:
    app: pro1
  type: NodePort
