apiVersion: v1
kind: Service
metadata:
  labels:
    app: pro1
  name: pro1-service
  namespace: pro
spec:
  ports:
    - port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: pro1
  type: NodePort
